"""
Django settings for CHOHEALT_BACK project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-kjpylr9@ev6_ld^b*a9kap2#_x(l)$y_6x-%taejra721u%)+l')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# In production this app sits behind Coolify's Traefik proxy, which terminates
# TLS and forwards plain HTTP internally — without this, request.is_secure()
# is always False, which breaks CSRF validation (and would mark the CSRF/
# session cookies as insecure) even on a real HTTPS request.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'storages',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    'adminpanel',
    'base',
    'billing',
    'delivery',
    'doctor',
    'medplum',
    'patient',
    'userauths',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CHOHEALT_BACK.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CHOHEALT_BACK.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # PostgreSQL propio (VPS), conexion interna dentro de la misma red Docker: no requiere SSL.
    db_config = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        ssl_require=os.getenv('DATABASE_SSL_REQUIRE', 'False') == 'True',
    )
    DATABASES = {'default': db_config}
else:
    # Fallback a SQLite para desarrollo local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'es'

LANGUAGES = (
    ('es', _('Spanish')),
    ('en', _('English')),
)


TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.getenv('AWS_STORAGE_BUCKET_NAME', 'chohealth-media'),
            "endpoint_url": os.getenv('AWS_S3_ENDPOINT_URL'),
            "access_key": os.getenv('AWS_ACCESS_KEY_ID'),
            "secret_key": os.getenv('AWS_SECRET_ACCESS_KEY'),
            "region_name": os.getenv('AWS_S3_REGION_NAME', 'us-east-1'),
            "addressing_style": "path",
            "default_acl": None,
            "querystring_auth": False,
            "file_overwrite": False,
            "custom_domain": os.getenv('AWS_S3_CUSTOM_DOMAIN'),
        },
    },
    "staticfiles": {
        # Algunos archivos vendorizados (ej. bootstrap.bundle.min.js de Jazzmin) referencian
        # un .map que no viene incluido; la variante "Manifest" hace fallar collectstatic por eso.
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Solo usado por el comando de migracion one-off que trae los archivos historicos desde Cloudinary.
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', '')


# Jazzmin Admin UI Configuration
JAZZMIN_SETTINGS = {
    "site_title": "CHO Health Admin",
    "site_header": "CHO Health",
    "site_brand": "CHO Health",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Bienvenido a CHO Health",
    "copyright": "CHO Health",

    "search_model": ["userauths.User"],

    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "base": "fas fa-hospital",
        "billing": "fas fa-file-invoice-dollar",
        "doctor": "fas fa-user-md",
        "patient": "fas fa-procedures",
        "userauths": "fas fa-id-card",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    "show_theme_chooser": True,

    "custom_css": "jazzmin/css/custom.css",
    "custom_js": "jazzmin/js/custom.js",

    "changeform_format": "horizontal_tabs",
}

AUTH_USER_MODEL = 'userauths.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000'
).split(',')

# Needed for Django admin (Jazzmin) login to work in production — without
# this, the proxy setup above means Django computes the request's own origin
# as http://, which never matches the https:// Origin/Referer a real browser
# sends, and every POST (including login) is rejected as a CSRF failure.
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'https://chohealth-api.cristianpuentes.com,https://chohealth.cristianpuentes.com,http://localhost:3000'
).split(',')

# Stripe
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# PayPal
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', '')
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')

# Email (SMTP via Postal, self-hosted mailer — replaces SendGrid)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'mail.cristianpuentes.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', '')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')
PASSWORD_RESET_TOKEN_EXPIRY_HOURS = 1

# Jitsi Meet (self-hosted, JWT-secured) — video calls for virtual appointments
JITSI_BASE_URL = os.getenv('JITSI_BASE_URL', 'https://meet.cristianpuentes.com')
JITSI_APP_ID = os.getenv('JITSI_APP_ID', 'chohealth')
JITSI_APP_SECRET = os.getenv('JITSI_APP_SECRET', '')
JITSI_JWT_AUDIENCE = os.getenv('JITSI_JWT_AUDIENCE', 'jitsi')
JITSI_JWT_SUB = os.getenv('JITSI_JWT_SUB', 'meet.cristianpuentes.com')
JITSI_JWT_TTL_MINUTES = int(os.getenv('JITSI_JWT_TTL_MINUTES', '120'))
JITSI_ROOM_SALT = os.getenv('JITSI_ROOM_SALT', SECRET_KEY)
# Temporary testing escape hatch — skips the "only around appointment time"
# window on the join-token endpoint. Meant to be turned back off afterwards.
JITSI_SKIP_TIME_WINDOW = os.getenv('JITSI_SKIP_TIME_WINDOW', 'False') == 'True'

# Medplum (FHIR server, self-hosted). Disabled by default so local dev / CI
# doesn't need a running Medplum instance — messaging endpoints degrade to
# 503 when this is False, everything else in the app is unaffected.
MEDPLUM_ENABLED = os.getenv('MEDPLUM_ENABLED', 'False') == 'True'
MEDPLUM_BASE_URL = os.getenv('MEDPLUM_BASE_URL', 'https://medplum-api.cristianpuentes.com')
MEDPLUM_CLIENT_ID = os.getenv('MEDPLUM_CLIENT_ID', '')
MEDPLUM_CLIENT_SECRET = os.getenv('MEDPLUM_CLIENT_SECRET', '')
MEDPLUM_TIMEOUT = (5, 15)

JAZZMIN_UI_TWEAKS = {
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-light-primary",
    "theme": "cerulean",
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

