# Generated by Django 6.0.3 on 2026-04-09 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdispute',
            name='filed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_disputes', to='patient.patient'),
        ),
    ]
