# Generated by Django 6.0.3 on 2026-04-12 01:17

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_invoice_polymorphic_target'),
        ('billing', '0004_alter_billingdispute_sid_alter_invoice_sid_and_more'),
        ('patient', '0006_invoice_polymorphic_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='medicine_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='base.medicineorder'),
        ),
        migrations.AlterField(
            model_name='billingdispute',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='base.appointment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('appointment__isnull', False), ('medicine_order__isnull', True)), models.Q(('appointment__isnull', True), ('medicine_order__isnull', False)), _connector='OR'), name='invoice_exactly_one_target'),
        ),
    ]
