# Generated by Django 6.0.3 on 2026-04-02 20:14

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
