# Generated by Django 6.0.3 on 2026-04-09 04:04

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Antibiotic', 'Antibiotic'), ('Painkiller', 'Painkiller'), ('Anti-inflammatory', 'Anti-inflammatory'), ('Antihypertensive', 'Antihypertensive'), ('Antidiabetic', 'Antidiabetic'), ('Antihistamine', 'Antihistamine'), ('Antidepressant', 'Antidepressant'), ('Vitamin', 'Vitamin'), ('Supplement', 'Supplement'), ('Other', 'Other')], default='Other', max_length=50)),
                ('dosage_form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Other', 'Other')], default='Tablet', max_length=50)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_prescription', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_appointments', to='base.laborder'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='is_prescribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborder',
            name='source_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_lab_orders', to='base.appointment'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='delivery_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_pickups', to='base.branch'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='delivery_method',
            field=models.CharField(choices=[('external', 'External'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], default='external', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='is_system_medication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='base.medication'),
        ),
    ]
