# Generated by Django 6.0.3 on 2026-04-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_medication_cost_alter_appointment_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('system', 'System')], max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
