# Generated by Django 6.0.3 on 2026-04-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_appointment_cancel_reason_appointment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(
                choices=[
                    ('Unpaid', 'Unpaid'),
                    ('Scheduled', 'Scheduled'),
                    ('Confirmed', 'Confirmed'),
                    ('In Progress', 'In Progress'),
                    ('Completed', 'Completed'),
                    ('Cancelled', 'Cancelled'),
                    ('No Show', 'No Show'),
                ],
                default='Scheduled',
                max_length=20,
            ),
        ),
    ]
