# Generated by Django 6.0.3 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_migrate_scheduled_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(
                choices=[
                    ('Unpaid', 'Unpaid'),
                    ('Confirmed', 'Confirmed'),
                    ('In Progress', 'In Progress'),
                    ('Completed', 'Completed'),
                    ('Cancelled', 'Cancelled'),
                    ('No Show', 'No Show'),
                ],
                default='Unpaid',
                max_length=20,
            ),
        ),
    ]
