# Generated by Django 6.0.3 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_scheduled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='free_when_prescribed',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'When True, a patient receives this medication free of charge if it comes '
                    'from a prescription issued by a doctor of the hospital. Patients purchasing '
                    'the medication directly (without a prescription) still pay the full cost.'
                ),
            ),
        ),
    ]
