# Generated by Django 6.0.3 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_medication_free_when_prescribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderitem',
            name='source_prescription_item',
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=models.deletion.SET_NULL,
                related_name='medicine_order_item',
                to='base.prescriptionitem',
                help_text=(
                    'If this order item fulfils a doctor prescription, links to the '
                    'specific PrescriptionItem being claimed. Used to enforce that a '
                    'prescribed medication is retrieved at most once.'
                ),
            ),
        ),
    ]
