# Generated by Django 6.0.3 on 2026-04-14 00:34

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_appointment_sid_alter_branch_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='source_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='base.prescription'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicineorderitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.CreateModel(
            name='MedicineDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('stage', models.CharField(choices=[('picked_up', 'Picked up from origin'), ('left_origin', 'Left the branch'), ('on_the_way', 'On the way'), ('arriving_soon', 'Arriving soon'), ('delivered', 'Delivered')], default='picked_up', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='base.medicineorder')),
                ('origin_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='base.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
