# Generated by Django 6.0.3 on 2026-04-14 01:20

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_appointment_sid_alter_branch_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='laborderitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicinedelivery',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='medicineorderitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
