# Generated by Django 6.0.3 on 2026-09-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_messaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='attachment_binary_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
