# Generated by Django 6.0.3 on 2026-09-08 00:37
# Hand-cleaned: dropped the unrelated shortuuid `sid` AlterField noise that
# `makemigrations` proposes on every model (shortuuid.uuid vs
# shortuuid.main.ShortUUID.uuid version drift), and inserted the
# merge_duplicate_threads data migration ahead of the new unique constraint.

import django.db.models.deletion
from django.db import migrations, models


def merge_duplicate_threads(apps, schema_editor):
    """Collapse any existing one-thread-per-appointment duplicates into a
    single thread per (patient, doctor), so the new unique constraint below
    can be applied. For each duplicate group, the oldest thread is kept as
    canonical (its `opened_at` is the relationship's real start); every
    other thread's messages are reassigned onto it, read receipts are
    merged (keeping the most recent `last_read_at` per user), and the
    canonical thread ends up pointing at whichever appointment in the group
    is the most recent.
    """
    MessageThread = apps.get_model('base', 'MessageThread')
    ThreadMessage = apps.get_model('base', 'ThreadMessage')
    ThreadRead = apps.get_model('base', 'ThreadRead')
    from django.db.models import Count

    duplicate_pairs = (
        MessageThread.objects.values('patient_id', 'doctor_id')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
    )

    for pair in duplicate_pairs:
        threads = list(
            MessageThread.objects
            .filter(patient_id=pair['patient_id'], doctor_id=pair['doctor_id'])
            .select_related('appointment')
            .order_by('opened_at')
        )
        canonical = threads[0]
        touched = False

        for dup in threads[1:]:
            ThreadMessage.objects.filter(thread=dup).update(thread=canonical)

            for read in ThreadRead.objects.filter(thread=dup):
                existing = ThreadRead.objects.filter(thread=canonical, user_id=read.user_id).first()
                if existing:
                    if read.last_read_at > existing.last_read_at:
                        # .update(), not .save() — last_read_at has auto_now=True,
                        # which would silently overwrite this historical value
                        # with "now" if set through an instance save() instead.
                        ThreadRead.objects.filter(pk=existing.pk).update(last_read_at=read.last_read_at)
                    read.delete()
                else:
                    read.thread = canonical
                    read.save(update_fields=['thread'])

            if dup.appointment.date > canonical.appointment.date:
                canonical.appointment_id = dup.appointment_id
                canonical.status = dup.status
                touched = True

            dup.delete()

        canonical.message_count = canonical.messages.count()
        last_msg = canonical.messages.order_by('-sent_at').first()
        if last_msg:
            canonical.last_message_at = last_msg.sent_at
            touched = True
        if touched or canonical.message_count:
            canonical.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_threadmessage_attachment_binary_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagethread',
            options={'ordering': ['-appointment__date', '-last_message_at']},
        ),
        migrations.AddField(
            model_name='messagethread',
            name='reactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='base.appointment'),
        ),
        migrations.RunPython(merge_duplicate_threads, migrations.RunPython.noop),
    ]
