# Generated by Django 6.0.3 on 2026-09-10 03:58
# Hand-cleaned: dropped the unrelated shortuuid `sid` AlterField noise that
# `makemigrations` proposes on every model (shortuuid.uuid vs
# shortuuid.main.ShortUUID.uuid version drift).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_branch_coordinates'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedelivery',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliveryperson'),
        ),
        migrations.AddField(
            model_name='medicinedelivery',
            name='proof_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='medicinedelivery',
            name='proof_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='medicinedelivery',
            name='proof_photo',
            field=models.FileField(blank=True, upload_to='delivery_proof'),
        ),
    ]
