# Generated by Django 6.0.3 on 2026-09-10 04:09
# Hand-cleaned: dropped the unrelated shortuuid `sid` AlterField noise that
# `makemigrations` proposes on every model (shortuuid.uuid vs
# shortuuid.main.ShortUUID.uuid version drift).
#
# Drops 'left_origin' and 'arriving_soon' from MedicineDelivery.stage —
# those were only ever set by the old time-based simulation, which is gone.
# Verified against production data first: both existing rows were already
# 'delivered', so no data migration is needed.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_medicinedelivery_courier_and_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedelivery',
            name='stage',
            field=models.CharField(choices=[('picked_up', 'Picked up from origin'), ('on_the_way', 'On the way'), ('delivered', 'Delivered')], default='picked_up', max_length=20),
        ),
    ]
