# Generated by Django 6.0.3 on 2026-09-01 03:48

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_alter_user_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
