# Generated by Django 6.0.3 on 2026-09-10 03:58
# Hand-cleaned: dropped the unrelated shortuuid `sid` AlterField noise that
# `makemigrations` proposes on every model (shortuuid.uuid vs
# shortuuid.main.ShortUUID.uuid version drift).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_alter_user_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Delivery', 'Delivery'), ('Superuser', 'Superuser')], default='Patient', max_length=20),
        ),
    ]
