# Generated by Django 6.0.3 on 2026-09-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_alter_patient_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medplum_patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
