# Generated by Django 6.0.3 on 2026-09-10 03:58
# Hand-cleaned: dropped the unrelated shortuuid `sid` AlterField noise that
# `makemigrations` proposes on every model (shortuuid.uuid vs
# shortuuid.main.ShortUUID.uuid version drift).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_patient_medplum_patient_id_alter_patient_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gps_tracking_consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
