# Generated by Django 6.0.3 on 2026-04-02 19:47

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True)),
                ('image', models.FileField(blank=True, default='default/default-user.jpg', upload_to='doctor_images')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('first_last_name', models.CharField(max_length=100)),
                ('second_last_name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('specialization', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=300)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('next_available_appointment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True)),
                ('type', models.CharField(choices=[('New Appointment', 'New Appointment'), ('Appointment Cancelled', 'Appointment Cancelled'), ('Appointment Rescheduled', 'Appointment Rescheduled')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
