# Generated by Django 6.0.3 on 2026-04-20 05:10

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_doctor_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='doctor',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorqualification',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Appointment', 'New Appointment'), ('Appointment Confirmed', 'Appointment Confirmed'), ('Appointment Cancelled', 'Appointment Cancelled'), ('Appointment Completed', 'Appointment Completed'), ('Appointment Rescheduled', 'Appointment Rescheduled'), ('Payment Received', 'Payment Received'), ('Lab Results Ready', 'Lab Results Ready'), ('Medical Record Available', 'Medical Record Available'), ('Prescription Ready', 'Prescription Ready'), ('Lab Order Created', 'Lab Order Created'), ('Medication Ready for Pickup', 'Medication Ready for Pickup'), ('Medication Dispatched', 'Medication Dispatched'), ('Medication Delivered', 'Medication Delivered'), ('Rate Doctor', 'Rate Doctor')], max_length=50),
        ),
    ]
