# Generated by Django 6.0.3 on 2026-09-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_alter_doctor_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='medplum_practitioner_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
