# Generated by Django 6.0.3 on 2026-09-10 03:58
# Hand-cleaned: dropped the unrelated shortuuid `sid` AlterField noise that
# `makemigrations` proposes on every model (shortuuid.uuid vs
# shortuuid.main.ShortUUID.uuid version drift).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_branch_coordinates'),
        ('doctor', '0019_notification_new_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='base.medicinedelivery'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Appointment', 'New Appointment'), ('Appointment Confirmed', 'Appointment Confirmed'), ('Appointment Cancelled', 'Appointment Cancelled'), ('Appointment Completed', 'Appointment Completed'), ('Appointment Rescheduled', 'Appointment Rescheduled'), ('Payment Received', 'Payment Received'), ('Lab Results Ready', 'Lab Results Ready'), ('Medical Record Available', 'Medical Record Available'), ('Prescription Ready', 'Prescription Ready'), ('Lab Order Created', 'Lab Order Created'), ('Medication Ready for Pickup', 'Medication Ready for Pickup'), ('Medication Dispatched', 'Medication Dispatched'), ('Medication Delivered', 'Medication Delivered'), ('Rate Doctor', 'Rate Doctor'), ('New Message', 'New Message'), ('New Delivery Offer', 'New Delivery Offer')], max_length=50),
        ),
    ]
